### ISSUE TITLE
Rebuild with remove-overlaps applied

### ISSUE THREAD

**Issue by davelab6** [enathu/kavivanar#2]
There are some problems with spline directions and remove overlaps:

<img width="706" alt="screen shot 2016-03-25 at 11 32 24" src="https://cloud.githubusercontent.com/assets/261579/14047273/47c1b7ba-f27d-11e5-805c-79eaebaa413f.png">

**Comment by enathu** [comment]
Fixed (https://github.com/enathu/kavivanar/commit/ef0b7bd836c8c41bd3b6fe7b093dbd86daad1b6d) :)
