### ISSUE TITLE
© and ® are thin

### ISSUE THREAD

**Issue by davelab6** [enathu/kavivanar#3]
© and ® are much have much lighter strokes than the rest of the design. This is not urgent but it would be good to fix in the future :)

**Comment by davelab6** [comment]
<img width="559" alt="screen shot 2016-04-05 at 11 44 12" src="https://cloud.githubusercontent.com/assets/261579/14288213/be528c5c-fb23-11e5-8ce8-383ce0f06a21.png">

**Comment by enathu** [comment]
Fixed. :)
