### ISSUE TITLE
Minor things 2

### ISSUE THREAD

**Issue by davelab6** [enathu/kavivanar#6]
- [x] FFTM table still included. 
- [x] Please add your build script or describe your process :)
- [x] Set version number to v1.88
- [x] remove nameID 16 and 17

```
    <namerecord nameID="16" platformID="3" platEncID="1" langID="0x409">
      Kavivanar
    </namerecord>
    <namerecord nameID="17" platformID="3" platEncID="1" langID="0x409">
      Regular
    </namerecord>
```

Hotfix'd ttf included:

[Kavivanar-Regular.ttf.zip](https://github.com/enathu/kavivanar/files/206458/Kavivanar-Regular.ttf.zip)

**Comment by enathu** [comment]
Fixed :)
